version: '3'
services:
  gitlab-ce:
    image: gitlab/gitlab-ce
    environment:
      - GITLAB_ROOT_PASSWORD=password
      - GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN=c8151a7a-1407-42cd-af3a-dd6e226816e2
    ports:
      - 80:80
  gitlab-runner:
    build: ./gitlab-runner
    environment:
      - CI_SERVER_HOST=gitlab-ce
      - CI_SERVER_PORT=80
      - REGISTRATION_TOKEN=c8151a7a-1407-42cd-af3a-dd6e226816e2
      - REGISTER_NON_INTERACTIVE=true
      - REGISTER_LOCKED=false
      - RUNNER_SHELL=bash
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine
      - CI_SERVER_URL=http://gitlab-ce/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - gitlab-ce
