version: '3'
services:
  gitlab-ce:
    image: gitlab/gitlab-ce
    environment:
      - GITLAB_ROOT_PASSWORD=password
      - GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN=c8151a7a-1407-42cd-af3a-dd6e226816e2
    ports:
      - 80:80
  gitlab-runner:
    build: ./gitlab-runner
    environment:
      - CI_SERVER_HOST=gitlab-ce
      - CI_SERVER_PORT=80
      - CI_SERVER_URL=http://gitlab-ce
      - CLONE_URL=http://gitlab-ce
      - REGISTRATION_TOKEN=c8151a7a-1407-42cd-af3a-dd6e226816e2
      - REGISTER_NON_INTERACTIVE=true
      - REGISTER_LOCKED=false
      - REGISTRY_HOST=localhost:5000
      - RUNNER_SHELL=bash
      - RUNNER_EXECUTOR=shell
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - gitlab-ce
  project-importer:
    build: ./project-importer
    environment:
      - GITLAB_ROOT_PASSWORD=password
    links:
      - gitlab-ce
  registry:
    image: registry:2
    ports:
      - '5000:5000'
